---
- name: Splunk webhook test
  hosts: localhost
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
        token: "{{ EDA_TOKEN | default('splunktoken') }}"
  rules:
    - name: trigger JT when error_type == disk_full
      condition: >
        event.payload is defined and
        event.payload.result is defined and
        event.payload.result.error_type is defined and
        event.payload.result.error_type == "disk_full" 
      action:
        run_playbook:
          name: playbooks/splunk_disk_full.yml
          extra_vars:
            incident_time: "{{ event.payload.result._time | default('') }}"
            target_host: "{{ event.payload.result.host | default('') }}"
            percent_used: "{{ event.payload.result.percent_used | default(omit) }}"
            source: "webhook"
