- name: Test webhook activation
  hosts: localhost
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: Always fire on any event
      condition: "event is defined"
      action:
        debug:
          msg: "Received event: {{ event }}"
